# Generated by Django 4.1.7 on 2023-02-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_auto_20230217_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractor',
            name='on_check',
            field=models.BooleanField(default=False, verbose_name='on_check'),
        ),
        migrations.AlterField(
            model_name='subcontractor',
            name='telegram_id',
            field=models.CharField(max_length=50, verbose_name='chat id'),
        ),
    ]
