# Generated by Django 4.1.7 on 2023-02-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_subcontractor_on_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractor',
            name='chat_id',
            field=models.CharField(default=333, max_length=50, verbose_name='chat id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcontractor',
            name='telegram_id',
            field=models.CharField(max_length=50, verbose_name='telegram id'),
        ),
    ]
