# Generated by Django 4.1.7 on 2023-02-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_subcontractor_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractor',
            name='status',
            field=models.CharField(choices=[('on_check', 'На одобрении'), ('enable', 'Подтвержден'), ('disable', 'Заблокирован')], default=('disable', 'Заблокирован'), max_length=10),
        ),
    ]
